### ISSUE TITLE
Real time encoding

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [w3reality/async-thread-worker#9]
Is this project can encode in real time? frame by frame from a buffer and send data with rtcdatachannel or websocket?

**Comment by j-devel** [comment]
> encode in real time?

Definitely not possible by the encoder [used in the demo](https://w3reality.github.io/async-thread-worker/examples/wasm-ffmpeg/index.html).  I think you will need something else that's more optimised to your situation...

**Comment by ROBERT-MCDOWELL** [comment]
ok thanks, I will try to check the code to see if it's possible with ffmpeg
